power <- read.csv("household_power_consumption.csv", sep = ";", stringsAsFactors = F, na.strings="?")
format <- data.frame(strptime(paste(power$Date, power$Time, sep = " "), format = "%d/%m/%Y %H:%M:%S"), power[3:9])
names(format)[1] <- "time"
startDate <- as.POSIXlt("2007-02-01 00:00:00")
endDate <- as.POSIXlt("2007-02-03 00:00:00")
timeFrame <- subset(format, time >= startDate & time < endDate)
plot(timeFrame$time, timeFrame$Sub_metering_1, type = "l", ylab = "Energy Sub Metering", xlab = "")
lines(timeFrame$time, timeFrame$Sub_metering_2, type = "l", col = "red")
lines(timeFrame$time, timeFrame$Sub_metering_3, type = "l", col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(2, 2), lwd = c(2.5, 2.5), cex = 0.5, col = c("black", "blue", "red"))
dev.copy(png,'plot3.png')
dev.off()