power <- read.csv("household_power_consumption.csv", sep = ";", stringsAsFactors = F, na.strings="?")
format <- data.frame(strptime(paste(power$Date, power$Time, sep = " "), format = "%d/%m/%Y %H:%M:%S"), power[3:9])
names(format)[1] <- "time"
startDate <- as.POSIXlt("2007-02-01 00:00:00")
endDate <- as.POSIXlt("2007-02-03 00:00:00")
timeFrame <- subset(format, time >= startDate & time < endDate)
png("plot3.png", width = 3.25, height = 3.25, units = "in", res = 1200, pointsize = 4)
par(mfrow=c(1, 1), lwd = 0.7)
plot(timeFrame$time, timeFrame$Sub_metering_1, type = "l", ylab = "Energy Sub Metering", xlab = "")
lines(timeFrame$time, timeFrame$Sub_metering_2, type = "l", col = "red")
lines(timeFrame$time, timeFrame$Sub_metering_3, type = "l", col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1, 1), lwd = c(1.5, 1.5), cex = 1, col = c("black", "blue", "red"))
dev.off()